# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:  https://magicalee.github.io
date_format: "ordinal"
title: 麻吉卡的部落格
subtitle: "The Beginning of the End"

# for SEO, 會標記在首頁的 meta tags 內
description: "麻吉卡的部落格"
keywords: BlockChain,Hyperledger,Ethereum,

favicon: 
timezone: Asia/Taipei
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Magica Lee
organization: 
organization_url: 
github_username: magicalee
location: Taipei, Taiwan
email: b00505005@ntu.edu.tw

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首頁

  -
    href: /tags/
    label: 標籤

  -
    href: /categories/
    label: 主題分類

#  -
#    href: /wiki/
#    label: Wiki

#  -
#    href: /links/
#    label: Links

  -
    href: /codes/
    label: 我的程式碼

  -
    href: /about/
    label: 關於我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 5
lsi: false
quiet: false
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:slug/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #


disqus_username: disqus_JfXyP15KbI
#fb_appid: 500757300092333


# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-108281926-1


# script
debug: false